/*
 * MeMaS DP APIs
 * This is the Data Plane client for MeMaS (Memory Management Service).  See https://github.com/memas-ai/MeMaS for more details.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memasclient.model;

import ai.memas.memasclient.model.Citation;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MemorizeRequest
 */
public class MemorizeRequestTest {
    private final MemorizeRequest model = new MemorizeRequest();

    /**
     * Model tests for MemorizeRequest
     */
    @Test
    public void testMemorizeRequest() {
        // TODO: test MemorizeRequest
    }

    /**
     * Test the property 'document'
     */
    @Test
    public void documentTest() {
        // TODO: test document
    }

    /**
     * Test the property 'citation'
     */
    @Test
    public void citationTest() {
        // TODO: test citation
    }

    /**
     * Test the property 'corpusPathname'
     */
    @Test
    public void corpusPathnameTest() {
        // TODO: test corpusPathname
    }

}
