/*
 * MeMaS DP APIs
 * This is the Data Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memasclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RememberRequestAllOf
 */
public class RememberRequestAllOfTest {
    private final RememberRequestAllOf model = new RememberRequestAllOf();

    /**
     * Model tests for RememberRequestAllOf
     */
    @Test
    public void testRememberRequestAllOf() {
        // TODO: test RememberRequestAllOf
    }

    /**
     * Test the property 'corpusPathname'
     */
    @Test
    public void corpusPathnameTest() {
        // TODO: test corpusPathname
    }

}
