/*
 * MeMaS DP APIs
 * This is the Data Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memasclient.api;

import ai.memas.memasclient.invoker.ApiException;
import ai.memas.memasclient.model.CitedDocument;
import ai.memas.memasclient.model.RecollectRequest;
import ai.memas.memasclient.model.Remember200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DpApi
 */
@Disabled
public class DpApiTest {

    private final DpApi api = new DpApi();

    /**
     * Recollects
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recollectTest() throws ApiException {
        RecollectRequest recollectRequest = null;
        List<CitedDocument> response = api.recollect(recollectRequest);
        // TODO: test validations
    }

    /**
     * Memorize information
     *
     * Memorize information
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rememberTest() throws ApiException {
        CitedDocument citedDocument = null;
        Remember200Response response = api.remember(citedDocument);
        // TODO: test validations
    }

}
