/*
 * MeMaS DP APIs
 * This is the Data Plane client for MeMaS (Memory Management Service).  See https://github.com/memas-ai/MeMaS for more details.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memasclient.api;

import ai.memas.memasclient.invoker.ApiException;
import ai.memas.memasclient.model.CitedDocument;
import ai.memas.memasclient.model.Memorize200Response;
import ai.memas.memasclient.model.MemorizeRequest;
import ai.memas.memasclient.model.RecallRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DpApi
 */
@Disabled
public class DpApiTest {

    private final DpApi api = new DpApi();

    /**
     * Memorize information
     *
     * Memorize information
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void memorizeTest() throws ApiException {
        MemorizeRequest memorizeRequest = null;
        Memorize200Response response = api.memorize(memorizeRequest);
        // TODO: test validations
    }

    /**
     * Recalls information
     *
     * Recalls relevant information related to the given clue
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recallTest() throws ApiException {
        RecallRequest recallRequest = null;
        List<CitedDocument> response = api.recall(recallRequest);
        // TODO: test validations
    }

}
